name: RSpec

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} - ActiveSupport ${{ matrix.activesupport }}
    strategy:
      matrix:
        ruby:
          - '3.2'
          - '3.3'
          - '3.4'
        activesupport:
          - '6.1'
          - '7.0'
          - '7.1'
          - '7.2'
          - '8.0'
          - 'main'

    env:
      BUNDLE_GEMFILE: gemfiles/activesupport_${{ matrix.activesupport }}.gemfile
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: rspec
      run: bundle exec rake spec
